runtime: python27
api_version: 1
threadsafe: true
manual_scaling:
  instances: 1
handlers:
- url: /
  static_files: dist/bloom/index.html
  upload: dist/bloom/index.html
- url: /
  static_dir: dist/bloom
skip_files:
  - e2e/
  - node_modules/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE